name: Node CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [24.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and lint
      run: |
        npm ci
        npm run build --if-present
      env:
        CI: true
    - name: check format
      run: |
        npm run check-format
    - name: Run ESLint
      run: |
        npm run lint
